// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: client.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Flag          string                 `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskRequest) Reset() {
	*x = TaskRequest{}
	mi := &file_client_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskRequest) ProtoMessage() {}

func (x *TaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskRequest.ProtoReflect.Descriptor instead.
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *TaskRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *TaskRequest) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

type CrawlerTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	BillingType   string                 `protobuf:"bytes,4,opt,name=billing_type,json=billingType,proto3" json:"billing_type,omitempty"`
	CrawlNum      int32                  `protobuf:"varint,5,opt,name=crawl_num,json=crawlNum,proto3" json:"crawl_num,omitempty"`
	ExtraHeader   string                 `protobuf:"bytes,6,opt,name=extra_header,json=extraHeader,proto3" json:"extra_header,omitempty"`
	ReqMethod     string                 `protobuf:"bytes,7,opt,name=req_method,json=reqMethod,proto3" json:"req_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlerTask) Reset() {
	*x = CrawlerTask{}
	mi := &file_client_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlerTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerTask) ProtoMessage() {}

func (x *CrawlerTask) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerTask.ProtoReflect.Descriptor instead.
func (*CrawlerTask) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *CrawlerTask) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CrawlerTask) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CrawlerTask) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CrawlerTask) GetBillingType() string {
	if x != nil {
		return x.BillingType
	}
	return ""
}

func (x *CrawlerTask) GetCrawlNum() int32 {
	if x != nil {
		return x.CrawlNum
	}
	return 0
}

func (x *CrawlerTask) GetExtraHeader() string {
	if x != nil {
		return x.ExtraHeader
	}
	return ""
}

func (x *CrawlerTask) GetReqMethod() string {
	if x != nil {
		return x.ReqMethod
	}
	return ""
}

type CrawlerResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Tag           string                 `protobuf:"bytes,2,opt,name=tag,proto3" json:"tag,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	BillingType   string                 `protobuf:"bytes,4,opt,name=billing_type,json=billingType,proto3" json:"billing_type,omitempty"`
	CrawlNum      int32                  `protobuf:"varint,5,opt,name=crawl_num,json=crawlNum,proto3" json:"crawl_num,omitempty"`
	Runtime       int32                  `protobuf:"varint,6,opt,name=runtime,proto3" json:"runtime,omitempty"`
	StartTime     string                 `protobuf:"bytes,7,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	Success       bool                   `protobuf:"varint,8,opt,name=success,proto3" json:"success,omitempty"`
	ReqMethod     string                 `protobuf:"bytes,9,opt,name=req_method,json=reqMethod,proto3" json:"req_method,omitempty"`
	WebData       string                 `protobuf:"bytes,10,opt,name=web_data,json=webData,proto3" json:"web_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrawlerResult) Reset() {
	*x = CrawlerResult{}
	mi := &file_client_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlerResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlerResult) ProtoMessage() {}

func (x *CrawlerResult) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrawlerResult.ProtoReflect.Descriptor instead.
func (*CrawlerResult) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *CrawlerResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CrawlerResult) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *CrawlerResult) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *CrawlerResult) GetBillingType() string {
	if x != nil {
		return x.BillingType
	}
	return ""
}

func (x *CrawlerResult) GetCrawlNum() int32 {
	if x != nil {
		return x.CrawlNum
	}
	return 0
}

func (x *CrawlerResult) GetRuntime() int32 {
	if x != nil {
		return x.Runtime
	}
	return 0
}

func (x *CrawlerResult) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CrawlerResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CrawlerResult) GetReqMethod() string {
	if x != nil {
		return x.ReqMethod
	}
	return ""
}

func (x *CrawlerResult) GetWebData() string {
	if x != nil {
		return x.WebData
	}
	return ""
}

type HandleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleResponse) Reset() {
	*x = HandleResponse{}
	mi := &file_client_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleResponse) ProtoMessage() {}

func (x *HandleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleResponse.ProtoReflect.Descriptor instead.
func (*HandleResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *HandleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandleResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	EnableSpiders bool                   `protobuf:"varint,2,opt,name=enable_spiders,json=enableSpiders,proto3" json:"enable_spiders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_client_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *ControlRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ControlRequest) GetEnableSpiders() bool {
	if x != nil {
		return x.EnableSpiders
	}
	return false
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_client_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *ControlResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_client_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *StatusRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_client_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *StatusResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *StatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_client_proto protoreflect.FileDescriptor

const file_client_proto_rawDesc = "" +
	"\n" +
	"\fclient.proto\x12\aspiders\"7\n" +
	"\vTaskRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x12\n" +
	"\x04flag\x18\x02 \x01(\tR\x04flag\"\xc9\x01\n" +
	"\vCrawlerTask\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\fbilling_type\x18\x04 \x01(\tR\vbillingType\x12\x1b\n" +
	"\tcrawl_num\x18\x05 \x01(\x05R\bcrawlNum\x12!\n" +
	"\fextra_header\x18\x06 \x01(\tR\vextraHeader\x12\x1d\n" +
	"\n" +
	"req_method\x18\a \x01(\tR\treqMethod\"\x96\x02\n" +
	"\rCrawlerResult\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x10\n" +
	"\x03tag\x18\x02 \x01(\tR\x03tag\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12!\n" +
	"\fbilling_type\x18\x04 \x01(\tR\vbillingType\x12\x1b\n" +
	"\tcrawl_num\x18\x05 \x01(\x05R\bcrawlNum\x12\x18\n" +
	"\aruntime\x18\x06 \x01(\x05R\aruntime\x12\x1d\n" +
	"\n" +
	"start_time\x18\a \x01(\tR\tstartTime\x12\x18\n" +
	"\asuccess\x18\b \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"req_method\x18\t \x01(\tR\treqMethod\x12\x19\n" +
	"\bweb_data\x18\n" +
	" \x01(\tR\awebData\"D\n" +
	"\x0eHandleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"M\n" +
	"\x0eControlRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0eenable_spiders\x18\x02 \x01(\bR\renableSpiders\"C\n" +
	"\x0fControlResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"%\n" +
	"\rStatusRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"B\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x97\x02\n" +
	"\rSpiderService\x127\n" +
	"\aGetTask\x12\x14.spiders.TaskRequest\x1a\x14.spiders.CrawlerTask\"\x00\x12?\n" +
	"\n" +
	"HandleTask\x12\x16.spiders.CrawlerResult\x1a\x17.spiders.HandleResponse\"\x00\x12E\n" +
	"\x0eControlSpiders\x12\x17.spiders.ControlRequest\x1a\x18.spiders.ControlResponse\"\x00\x12E\n" +
	"\x10GetSpidersStatus\x12\x16.spiders.StatusRequest\x1a\x17.spiders.StatusResponse\"\x00B\tZ\a.;protob\x06proto3"

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData []byte
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)))
	})
	return file_client_proto_rawDescData
}

var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_client_proto_goTypes = []any{
	(*TaskRequest)(nil),     // 0: spiders.TaskRequest
	(*CrawlerTask)(nil),     // 1: spiders.CrawlerTask
	(*CrawlerResult)(nil),   // 2: spiders.CrawlerResult
	(*HandleResponse)(nil),  // 3: spiders.HandleResponse
	(*ControlRequest)(nil),  // 4: spiders.ControlRequest
	(*ControlResponse)(nil), // 5: spiders.ControlResponse
	(*StatusRequest)(nil),   // 6: spiders.StatusRequest
	(*StatusResponse)(nil),  // 7: spiders.StatusResponse
}
var file_client_proto_depIdxs = []int32{
	0, // 0: spiders.SpiderService.GetTask:input_type -> spiders.TaskRequest
	2, // 1: spiders.SpiderService.HandleTask:input_type -> spiders.CrawlerResult
	4, // 2: spiders.SpiderService.ControlSpiders:input_type -> spiders.ControlRequest
	6, // 3: spiders.SpiderService.GetSpidersStatus:input_type -> spiders.StatusRequest
	1, // 4: spiders.SpiderService.GetTask:output_type -> spiders.CrawlerTask
	3, // 5: spiders.SpiderService.HandleTask:output_type -> spiders.HandleResponse
	5, // 6: spiders.SpiderService.ControlSpiders:output_type -> spiders.ControlResponse
	7, // 7: spiders.SpiderService.GetSpidersStatus:output_type -> spiders.StatusResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_client_proto_rawDesc), len(file_client_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
