name: Build and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.21'

    - name: Build
      run: rm -rf ecsagent && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags="-w -s" -a -o ecsagent client.go

    - name: Archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: ecsagent
        path: ecsagent

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ecsagent

    - name: Commit and push changes
      run: |
        git config --global user.name "daily-update"
        git config --global user.email "tg@spiritlhl.top"
        git add .
        git commit -m "Add compiled artifact"
        git push
